package email

import (
	"html/template"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"

	"gopkg.in/gomail.v2"
)

var recipients = []string{
	"steven.gao@vinotech.com",
	"amuro.zhang@vinotech.com",
	"darren.zheng@vinotech.com",
	"catherine.li@vinotech.com",
	"polar.li@vinotech.com",
	"can.gunsiray@vinotech.com",
	"rika.gan@vinotech.com",
	"adel.lee@vinotech.com",
	"carlo.bischoff@vinotech.com",
	"zach.khoo@vinotech.com",
	"emmet.li@vinotech.com",
	"eden.wang@vinotech.com",
	"hazel.zhao@vinotech.com",
	"sebastian.faso@vinotech.com",
	"bluelue.yang@vinotech.com",
	"bruce.li@vinotech.com",
	"jacob.shi@vinotech.com",
	"frezen.zeng@vinotech.com",
	"echo.wang@vinotech.com",
	"funco.lin@vinotech.com",
	"rekkles.mai@vinotech.com",
	"michael.wu@vinotech.com",
	"leon.li@vinotech.com",
	"cary.yuan@vinotech.com",
	"floria.liu@vinotech.com",
	"rob.chiu@vinotech.com",
	"lucine.liu@vinotech.com",
	"helix.song@vinotech.com",
	"willis.lin@vinotech.com",
	"miya.guo@vinotech.com",
	"thanhtung.trang@vinotech.com",
	"crystal.li@vinotech.com",
	"krystal.li@vinotech.com",
	"gargi.zhu@vinotech.com",
	"vivi.park@vinotech.com",
	"phil.zhang@vinotech.com",
	"jason.zhang@vinotech.com",
	"samor.yan@vinotech.com",
	"eva.xie@vinotech.com",
	"alex.zhang@vinotech.com",
	"william.xu@vinotech.com",
	"bertha.zhou@vinotech.com",
	"maurizio.varriale@vinotech.com",
	"ali.mo@vinotech.com",
	"harry.bin@vinotech.com",
	"echoe.wan@vinotech.com",
	"tako.ma@vinotech.com",
	"faraz.ali@vinotech.com",
	"maki.wang@vinotech.com",
	"barry.xu@vinotech.com",
	"konstantin.permyakov@vinotech.com",
	"myra.wong@vinotech.com",
	"jennies.fan@vinotech.com",
	"kiki.zhao@vinotech.com",
	"yan.wong@vinotech.com",
	"jonny.huang@vinotech.com",
	"cloris.hua@vinotech.com",
	"alvin.kwok@vinotech.com",
	"bonnie.chen@vinotech.com",
	"sun.zhang@vinotech.com",
	"dylan.zhang@vinotech.com",
	"karen.hu@vinotech.com",
	"blake.he@vinotech.com",
	"henry.liang@vinotech.com",
	"flora.xian@vinotech.com",
	"stacy.zhu@vinotech.com",
	"winston.he@vinotech.com",
	"niki.li@vinotech.com",
	"eva.wang@vinotech.com",
	"cailen.cai@vinotech.com",
	"dai.shaola@vinotech.com",
	"maureen.ng@vinotech.com",
	"wilbur.wang@vinotech.com",
	"sooraj.palari@vinotech.com",
	"sue.su@vinotech.com",
	"kido.li@vinotech.com",
	"klaus.cai@vinotech.com",
	"joanna.cao@vinotech.com",
	"riley.zheng@vinotech.com",
	"andrei.zhebrun@vinotech.com",
	"msaber.neysaz@vinotech.com",
	"desmond.xiang@vinotech.com",
	"carina.wang@vinotech.com",
	"fion.zhang@vinotech.com",
	"nina.bai@vinotech.com",
	"chris.zhong@vinotech.com",
	"garen.xiao@vinotech.com",
	"amir.jahednia@vinotech.com",
	"emily.tu@vinotech.com",
	"ivy.zhang@vinotech.com",
	"kraus.liao@vinotech.com",
	"syesha.huang@vinotech.com",
	"pedro.gutierrez@vinotech.com",
	"roy.zhang@vinotech.com",
	"paphy.cai@vinotech.com",
	"jaqen.hu@vinotech.com",
	"ekko.huang@vinotech.com",
	"bryce.li@vinotech.com",
	"mika.zeng@vinotech.com",
	"ducky.wang@vinotech.com",
	"tom.cheng@vinotech.com",
	"bartek.juraszek@vinotech.com",
	"ivan.zhang@vinotech.com",
	"kelvin.ngo@vinotech.com",
	"larry.li@vinotech.com",
	"wendy.yang@vinotech.com",
	"olga.dubrova@vinotech.com",
	"louisa.lu@vinotech.com",
	"tania.li@vinotech.com",
	"mavis.cheng@vinotech.com",
	"raynal.wang@vinotech.com",
	"nicky.lin@vinotech.com",
	"walter.hu@vinotech.com",
	"laynee.lin@vinotech.com",
	"sheldon.xu@vinotech.com",
	"elvin.she@vinotech.com",
	"finin.liu@vinotech.com",
	"jeff.ko@vinotech.com",
	"liou.liu@vinotech.com",
	"wiriya.dangsiri@vinotech.com",
	"norman.jiang@vinotech.com",
	"yolanda.huang@vinotech.com",
	"nigel.chan@vinotech.com",
	"frey.pan@vinotech.com",
	"seven.liang@vinotech.com",
	"tony.huang@vinotech.com",
	"pelton.peng@vinotech.com",
	"mariusz.pilch@vinotech.com",
	"jerry.yuan@vinotech.com",
	"gary.yuan@vinotech.com",
	"mike.kim@vinotech.com",
	"jane.huang@vinotech.com",
	"sara.ebrahim@vinotech.com",
	"mira.zhou@vinotech.com",
	"lee.li@vinotech.com",
	"ceven.liu@vinotech.com",
	"shallot.yan@vinotech.com",
	"wynn.zhang@vinotech.com",
	"vita.lei@vinotech.com",
	"raina.lau@vinotech.com",
	"mollie.zhang@vinotech.com",
	"perry.wong@vinotech.com",
	"calvin.zhao@vinotech.com",
	"allen.lian@vinotech.com",
	"littlejane.gong@vinotech.com",
	"thom.buithi@vinotech.com",
	"stan.leung@vinotech.com",
	"kyra.chen@vinotech.com",
	"price.zhang@vinotech.com",
	"jojo.chen@vinotech.com",
	"leanet.valladares@vinotech.com",
	"frank.he@vinotech.com",
	"asher.li@vinotech.com",
	"will.guo@vinotech.com",
	"cindy.nan@vinotech.com",
	"underwood.xue@vinotech.com",
	"rania.liu@vinotech.com",
	"adam.wang@vinotech.com",
	"jonathan.mbaluka@vinotech.com",
	"caden.li@vinotech.com",
	"bandage.xia@vinotech.com",
	"yael.zhou@vinotech.com",
	"molly.chen@vinotech.com",
	"ray.wang@vinotech.com",
	"weil.liu@vinotech.com",
	"yvonne.guan@vinotech.com",
	"bethel.munachi@vinotech.com",
	"ethan.yang@vinotech.com",
	"zahra.mazaher@vinotech.com",
	"jessie.yan@vinotech.com",
	"omar.li@vinotech.com",
	"winter.yang@vinotech.com",
	"fredi.chen@vinotech.com",
	"nia.peng@vinotech.com",
	"chana.lam@vinotech.com",
	"morrey.meng@vinotech.com",
	"emma.zhou@vinotech.com",
	"ken.huang@vinotech.com",
	"moses.zhang@vinotech.com",
	"sharon.xie@vinotech.com",
	"renee.ding@vinotech.com",
	"hank.wang@vinotech.com",
	"lucas.ou@vinotech.com",
	"jude.zhang@vinotech.com",
	"evan.guan@vinotech.com",
	"vivian.chan@vinotech.com",
	"rachel.li@vinotech.com",
	"houndekon.merex@vinotech.com",
	"waiyu.lau@vinotech.com",
	"yan.deng@vinotech.com",
	"eira.li@vinotech.com",
	"shawn.sun@vinotech.com",
	"amjad.alhussein@vinotech.com",
	"mona.chen@vinotech.com",
	"gracy.ge@vinotech.com",
	"timson.kwok@vinotech.com",
	"sherry.su@vinotech.com",
	"heather.li@vinotech.com",
	"vv.deng@vinotech.com",
	"xixi.shi@vinotech.com",
	"mathias.wagner@vinotech.com",
	"sweet.tao@vinotech.com",
	"joyce.cheng@vinotech.com",
	"tiffany.li@vinotech.com",
	"dani.huang@vinotech.com",
	"aldosary.khaled@vinotech.com",
	"haruto.chen@vinotech.com",
	"skye.dong@vinotech.com",
	"penpen.li@vinotech.com",
	"zeev.zhao@vinotech.com",
	"cindy.cheung@vinotech.com",
	"hussein.alnajim@vinotech.com",
	"coral.cui@vinotech.com",
	"guron.gu@vinotech.com",
	"louis.lau@vinotech.com",
	"eugeo.xie@vinotech.com",
	"luis.suarez@vinotech.com",
	"shirley.wu@vinotech.com",
	"yolin.wu@vinotech.com",
	"mainda.kayoba@vinotech.com",
	"leo.tan@vinotech.com",
	"joyce.zhou@vinotech.com",
	"oreo.tang@vinotech.com",
	"naruto.jin@vinotech.com",
	"rolin.zhao@vinotech.com",
	"hack.zhong@vinotech.com",
	"andressa.pontes@vinotech.com",
	"jesse.zhou@vinotech.com",
	"drew.deng@vinotech.com",
	"seyedebrahim.mousavi@vinotech.com",
	"decpt.zhao@vinotech.com",
	"kay.wang@vinotech.com",
	"alex.rumondor@vinotech.com",
	"arlo.luo@vinotech.com",
	"rumy.jiang@vinotech.com",
	"muyun.lei@vinotech.com",
	"junior.brasil@vinotech.com",
	"ryann.cai@vinotech.com",
	"shary.zhuang@vinotech.com",
	"robert.quan@vinotech.com",
	"oscar.chan@vinotech.com",
	"joserafael.pena@vinotech.com",
	"sandra.zhou@vinotech.com",
	"nancy.fan@vinotech.com",
	"anna.pestova@vinotech.com",
	"simon.li@vinotech.com",
	"johnny.koon@vinotech.com",
	"raya.xu@vinotech.com",
	"grace.liu@vinotech.com",
	"diego.zuo@vinotech.com",
	"gigi.feng@vinotech.com",
	"stephanie.hernandez@vinotech.com",
	"efen.sun@vinotech.com",
	"leo.ng@vinotech.com",
	"pawn.jiang@vinotech.com",
	"boman.chui@vinotech.com",
	"zane.yang@vinotech.com",
	"sarah.li@vinotech.com",
	"snow.wang@vinotech.com",
	"zacker.ke@vinotech.com",
	"john.ruan@vinotech.com",
	"arvand.pedram@vinotech.com",
	"siavash.ru@vinotech.com",
	"shelin.xue@vinotech.com",
	"noodles.chen@vinotech.com",
	"walden.wu@vinotech.com",
	"diana.rizal@vinotech.com",
	"fiona.han@vinotech.com",
	"aaron.gu@vinotech.com",
	"eric.zhou@vinotech.com",
	"lily.guan@vinotech.com",
	"laine.wang@vinotech.com",
	"paul.zhang@vinotech.com",
	"becky.chen@vinotech.com",
	"gabriel.chen@vinotech.com",
	"sadqe.alia@vinotech.com",
	"Malik.Abbas@vinotech.com",
	"logan.li@vinotech.com",
	"cain.zhou@vinotech.com",
	"enver.g@vinotech.com",
	"joe.chou@vinotech.com",
	"houhou.bao@vinotech.com",
	"selina.huang@vinotech.com",
	"anton.tsarenok@vinotech.com",
	"iris.liu@vinotech.com",
	"jeffrey.zhao@vinotech.com",
	"zoey.jiang@vinotech.com",
	"reza.e@vinotech.com",
	"dv.giang@vinotech.com",
	"trey.miao@vinotech.com",
	"daneel.liu@vinotech.com",
	"robin.luo@vinotech.com",
	"haipo.yang@vinotech.com",
}

var tmpls = []string{`mining_start.html`}

var tmplSubjectMap = map[string]string{
	`mining_start.html`: "【Coinex】挖矿开启：存入CET，瓜分 80,000 SWCH",
	`coupon.html`:       "【CoinEx】恭喜获得5 USDT合约体验金，快来领取吧～",
	`bitcoinasia.html`:  "Your Ticket To Bitcoin Asia",
}

var tmplHeaderMap = map[string]string{
	`mining_start.html`: "header.png",
	`coupon.html`:       "header.png",
	`bitcoinasia.html`:  "bitcoin_header.png",
}

func ExampleNewClient() {
	for _, recipient := range recipients {
		htmlTmpl := `coupon.html`
		subject := tmplSubjectMap[htmlTmpl]
		m := gomail.NewMessage()
		m.SetHeader("From", m.FormatAddress(`coiinex.noreply@gmail.com`, `CoinEx`))
		m.SetHeader("To", recipient)
		m.SetHeader("Subject", subject)
		tmpl, err := template.New(filepath.Base(htmlTmpl)).ParseFiles(htmlTmpl)
		if err != nil {
			panic(err)
		}
		var htmlBody string
		writer := &strings.Builder{}
		if err := tmpl.Execute(writer, map[string]string{`recipientName`: recipient}); err != nil {
			panic(err)
		}
		htmlBody = writer.String()
		m.SetBody("text/html", htmlBody)
		header := tmplHeaderMap[htmlTmpl]
		m.Embed(header,
			gomail.SetHeader(map[string][]string{
				"Content-ID": {"header"}, // 注意尖括号包裹
			}),
		)

		//cli := NewClient(`linhongzhao.jp@gmail.com`, `viwhdswvqgtgatdm`)
		cli := NewClient(`coiinex.noreply@gmail.com`, `fwacdxhaiuskrugy`)
		//cli := NewClient(`vino.hr.2@gmail.com`, `banuzjvlxcqzphzt`)
		//cli := NewClient(`noreplyn6382@gmail.com`, `tittsvnvutvfwtzt`)
		err = cli.dialer.DialAndSend(m)
		if err != nil {
			panic(err)
		}
	}
	// Output:
	//
}

func FuzzNewClient(f *testing.F) {
	f.Add(`coiinex.noreply@gmail.com`)
	f.Add(`123456qweasd`)

	f.Fuzz(func(t *testing.T, sender string, password string) {
		rev := NewClient(sender, password)

	})
}
